/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stocksnstuff.gui;

import javax.swing.JOptionPane;
import stocksnstuff.database.DBIO.DBReader;

/**
 *
 * @author Mitchell
 */
public class RecoverUserGUI extends javax.swing.JFrame {

    /**
     * Creates new form RecoverUser
     */
    public RecoverUserGUI() {
        initComponents();
        initSubComps();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eMailF = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        sqrSub = new javax.swing.JButton();
        sq2 = new javax.swing.JLabel();
        sqr1 = new javax.swing.JTextField();
        sq1 = new javax.swing.JLabel();
        sqr2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recover");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recover Account Information");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email Address/Username:");

        submit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        sqrSub.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        sqrSub.setText("Submit");
        sqrSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrSubActionPerformed(evt);
            }
        });

        sq2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sq2.setForeground(new java.awt.Color(255, 255, 255));
        sq2.setText("Security Question #2");

        sqr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqr1ActionPerformed(evt);
            }
        });

        sq1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sq1.setForeground(new java.awt.Color(255, 255, 255));
        sq1.setText("Security Question #1");

        sqr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqr2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sq1)
                            .addComponent(sq2))
                        .addGap(18, 18, 18)
                        .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eMailF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sqr1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sqr2)
                    .addComponent(sqrSub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(eMailF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sq1)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(sqr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(sq2)
                .addGap(10, 10, 10)
                .addComponent(sqr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sqrSub)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initSubComps(){
        
        sqrSub.setVisible(false);
        sqr1.setEditable(false);
        sqr2.setEditable(false);
        
    }
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        if (!validateFields()) {
            JOptionPane.showMessageDialog(rootPane, "Empty fields!");
        } else {
            DBReader dbR = new DBReader("\\dbs\\register.txt");
            dbR.validatePerms();
            if (!dbR.scanDB(eMailF.getText(), detectType())) {
                JOptionPane.showMessageDialog(rootPane, "Invalid Email/Username");
                eMailF.setText("");
            } else {
                //Succesfully confirmed existence of the user account, now prompt for security questions...
                String[] secDat = dbR.getSecurityQuestions();
                submit.setVisible(false);
                sq1.setText(secDat[0]);
                sqr1.setEditable(true);
                sq2.setText(secDat[2]);
                sqr2.setEditable(true);
                sqrSub.setVisible(true);

            }
        }

    }//GEN-LAST:event_submitActionPerformed

    private void sqrSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrSubActionPerformed
        // TODO add your handling code here:

        //Validate security question responses
        DBReader dbR = new DBReader("register.txt");
        if (!dbR.scanDBByID(sqr1.getText(), 4,eMailF.getText(),detectType()) || !dbR.scanDBByID(sqr2.getText(), 6,eMailF.getText(),detectType())) {
            JOptionPane.showMessageDialog(rootPane, "Invalid user credentials...");
            this.dispose();

        } else {
            //they were correct, open reseet / recover detail GUI
            UserDataGUI udG = new UserDataGUI(dbR.getUserIdentity()[0],dbR.getUserIdentity()[1]);
            udG.setVisible(true);
        }

    }//GEN-LAST:event_sqrSubActionPerformed

    private void sqr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqr2ActionPerformed

    private void sqr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqr1ActionPerformed

    public int detectType() {

        if (eMailF.getText().contains("@")) {
            return 0;
        }
        return 1;
    }

    public boolean validateFields() {

        if (eMailF.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecoverUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecoverUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecoverUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecoverUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecoverUserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eMailF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sq1;
    private javax.swing.JLabel sq2;
    private javax.swing.JTextField sqr1;
    private javax.swing.JTextField sqr2;
    private javax.swing.JButton sqrSub;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
